- .github/actions/cache-node-modules/action.yml
- .github/actions/setup-node/action.yml
- .github/workflows/chromatic_deploy.yml
- .github/workflows/development.yml
- package.json
`package.json` の Storybook のビルドコマンドを更新し、Chromaticをワークフローに統合しました。
- `package.json` での Storybook ビルドコマンドの変更
- ワークフローへのChromaticの統合
- Chromaticの統合により、CI/CDプロセスでUIコンポーネントの視覚テストが可能になりました。
---
We've made updates to the `package.json` by changing the Storybook build command and integrated Chromatic into our workflows.
- Changed the Storybook build command in `package.json`
- Added Chromatic integrations to our workflows
- With the Chromatic integration, we can now have visual testing for our UI components in the CI/CD process.
> WorkflowにChromaticへのデプロイを追加

- .github/workflows/publish-package.yml
- package.json
`package.json` のパッケージ名を変更し、GitHub Actions上でのパッケージ公開ワークフローを追加しました。
https://siva-inc.atlassian.net/browse/DSD-28
- `package.json` でのパッケージ名の変更
- GitHub Actionsにパッケージ公開ワークフローの追加
- この変更により、新しいパッケージ名での公開が可能になりました。また、GitHub Actionsを使用しての自動パッケージ公開も設定されました。
> chore: npmへ公開するworkflowを追加

- src/components/organisms/GlobalNavigation/GlobalNavigation.stories.tsx
- src/components/organisms/GlobalNavigation/GlobalNavigation.tsx
- src/components/organisms/GlobalNavigation/type.ts
menuとaccountの表示切り替え対応
ウイイレで使用
| Default |  Simplified (NEW✨) |
| ---- | ---- |
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=404-3323&mode=dev
https://siva-inc.atlassian.net/browse/WE-4?atlOrigin=eyJpIjoiNWFmMWRlYTQ1NGM3NDRjZjk2Y2ZmOTc3MmRkYTkzNGMiLCJwIjoiaiJ9
> [GlobalNavigation] menuとaccountの表示切り替え対応

- package.json
- src/components/molecules/Tab/Tab.stories.tsx
- src/components/molecules/Tab/TabArea/index.ts
- src/components/molecules/Tab/TabNavigation/index.ts
- src/components/molecules/Tab/TabPage/index.ts
The exporting method of `Tab` was incorrect 😅
> Fixed Tab component export

- .github/workflows/development.yml
Chromaticのビルド時間を減らすためにChromaticへのデプロイタイミングを制限した
- workflows/development.ymlでのchromaticのデプロイを削除
> chore:developmentのCIからChromaticへのデプロイを削除

- package.json
- src/components/molecules/InputElement/InputElement.stories.tsx
- src/components/molecules/InputElement/InputElement.tsx
- src/components/molecules/InputElement/type.ts
- dialog等でInputElementのdescriptionTextに文字列以外にもリンクが入る場合があるため、stringとReactElementもとれるように変更
- それに伴い、`descriptionText`から`description`に変更
- storyに`description`が`<a>`タグリンクを含む場合も追加
https://www.figma.com/file/8mkhOMue3eAQS6H11k6wQ8/Re-design?type=design&node-id=1994-75188&mode=dev
squadbeyond-frontendに対して既に`InputElement`を使用している部分には影響がある変更なので、マージ後にsquadbeyond-frontendの方で対応する
（今回は影響が小さいのですぐに対応できるが、大きい場合はどういったフローで対応すべきなのか。。。）
> Change type of InputElement's descriptionText

- package.json
- src/components/atoms/BreadcrumbItem/BreadcrumbItem.stories.tsx
- src/components/atoms/BreadcrumbItem/BreadcrumbItem.test.tsx
- src/components/atoms/BreadcrumbItem/BreadcrumbItem.tsx
- src/components/atoms/BreadcrumbItem/index.ts
- src/components/atoms/BreadcrumbItem/type.ts
- src/components/molecules/Breadcrumbs/Breadcrumbs.stories.tsx
- src/components/molecules/Breadcrumbs/Breadcrumbs.test.tsx
- src/components/molecules/Breadcrumbs/Breadcrumbs.tsx
- src/components/molecules/Breadcrumbs/const.ts
- src/components/molecules/Breadcrumbs/index.ts
- src/components/molecules/Breadcrumbs/type.ts
新しい`BreadcrumbItem`と`Breadcrumbs`コンポーネントを実装,Storybookを追加した
仕様は[Figma](https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=3935-7172&mode=design&t=0RprvFeTO5U9O0Z6-11)を参照 (不明な点があればご質問ください)
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=3935-7172&mode=design&t=0RprvFeTO5U9O0Z6-11
- BreadcrumbItemコンポーネントを追加
- Breadcrumbsコンポーネントを追加
なし
---
Implemented new `BreadcrumbItem` and `Breadcrumbs` components, added Storybook.
Refer to the specification in [Figma](https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=3935-7172&mode=design&t=0RprvFeTO5U9O0Z6-11) (please ask if there are any unclear points).
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=3935-7172&mode=de …
> feat: Add Breadcrumbs components

- package.json
- src/components/molecules/Popover/Popover.stories.tsx
- src/components/molecules/Popover/Popover.test.tsx
- src/components/molecules/Popover/Popover.tsx
- src/components/molecules/Popover/const.ts
- src/components/molecules/Popover/type.ts
- feat(Popover):✨Add click mode
- test(Popover):✅Add some tests
Popoverに`mode`propsを追加しました
これによりPopoverを開く際のトリガー(`click`, `hover`)を選択できるようになりました
- Popoverにpropsを追加
- `mode`: コンテンツを開くトリガーがクリックかホバーか
- `isOpen`: 開閉状態
> feat: Add `mode` props for Popover

- package.json
- src/components/atoms/Selector/SelectorList/SelectorListItem/SelectorListItem.tsx
- src/components/atoms/Selector/SelectorList/SelectorListItem/type.ts
- src/components/molecules/Dialog/Dialog.stories.tsx
- yarn.lock
#64の影響でエラーが出ていた箇所を修正しました
```
> Run yarn build
yarn run v1.22.21
$ tsc && vite build
Error: src/components/atoms/Selector/SelectorList/SelectorListItem/type.ts(5,11): error TS2314: Generic type 'OptionType' requires 1 type argument(s).
Error: src/components/atoms/Selector/SelectorList/SelectorListItem/type.ts(7,12): error TS2314: Generic type 'SelectorListProps' requires 1 type argument(s).
Error: src/components/molecules/Dialog/Dialog.stories.tsx(174,17): error TS2353: Object literal may only specify known properties, and 'id' does not exist in type 'OptionType<BaseOptionValue>'.
Error: src/components/molecules/Dialog/Dialog.stories.tsx(175,17): error TS2353: Object literal may only specify known properties, and 'id' does not exist in type 'OptionType<BaseOptionValue>'.
error Command …
```
> fix: Selector generic type errors

- package.json
- src/components/atoms/Selector/Selector.stories.tsx
- src/components/atoms/Selector/SelectorList/SelectorList.tsx
- src/components/atoms/Selector/SelectorList/SelectorListItem/SelectorListItem.tsx
- src/components/atoms/Selector/SelectorList/SelectorListItem/const.ts
- src/components/atoms/Selector/SelectorList/SelectorListItem/type.ts
- src/components/atoms/Selector/type.ts
- selectorのoptionsの各アイテムにdisabledを与えることができるよう修正
- disabledなoptionは文字色が薄くなりクリック不可になるよう修正
- [figma](https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=2197-18313&mode=design&t=Ums2yqhuIJxRPRcr-4)
- チケットはありません。以前モカさんと口頭でやり取りした際の修正依頼のためです
> セレクタのアイテムごとにdisabledをかけられるよう修正

- package.json
- src/components/atoms/DateRangePicker/DateRangePicker.test.tsx
- src/components/atoms/Tooltip/Tooltip.tsx
- src/components/atoms/Tooltip/type.ts
Tooltipの実装を更新しました
Tooltipの親要素スタイルにrelativeが指定されている場合にTooltipの座標指定がうまくいかず表示が崩れてしまうため、createPortalを使用して別ルートのDOMにTooltipを描画するようにしました。
またTooltipTextにReactNodeを受け取れるように変更しました。
Updated the implementation of Tooltip.
Due to the issue where tooltips were not positioning correctly and display was breaking when the parent element's style was set to relative, we now render the Tooltip in a different root DOM using createPortal. 
Also, TooltipText has been modified to accept ReactNode.
以下のような現象が起こっていました
The following phenomenon was occurring:
https://github.com/siva-squad/squad-ui/assets/19528768/16d2d958-08fb-4e9f-9419-5116abe1d6f8
Tooltipの変更
- createPortalを使用した形式に変更した
- TooltipTextでReactNodeを許容するように変更下
その他の変更
- DateRangePickerのテストが通っていなかったため暫定対応でtodoのtestに変更しました
Tooltip updates
- Changed to a …
> feat:Changed the tooltip to a format that uses Portal

- package.json
- src/components/atoms/Tooltip/Tooltip.tsx
ツールチップ内のテキストが画像のようにはみ出てしまう問題を修正しました
I fixed the issue where the text inside the tooltip overflows as shown in the image.
ツールチップテキストを表示する枠のwidth指定を削除した
I removed the width specification for the frame displaying the tooltip text.
> fix(Tooltip):💄 Fix tooltip width

- package.json
- src/components/atoms/Selector/Selector.stories.tsx
- src/components/atoms/Selector/Selector.tsx
- src/components/atoms/Selector/SelectorList/SelectorList.tsx
- src/components/atoms/Selector/SelectorList/type.ts
- src/components/atoms/Selector/hooks/useOutsideClick.ts
- src/components/atoms/Selector/type.ts
- yarn.lock
Selectorコンポーネントをタイトルの通り変更しました
beyondページのフォルダ移動ダイアログでキャプチャのように表示されてしまうため
- パッケージバージョンを更新
- リストのmaxHeightをpropskで指定できるように変更
- はみ出た場合はスクロール可能
- 他の要素と重ならないようにrect-portalを使用する形に変更
> feat:Change the selector to use react-portal

- src/components/molecules/ListItemDropDown/const.ts
- src/components/molecules/MenuList/MenuList.tsx
- src/components/molecules/MenuList/const.tsx
- src/components/molecules/MenuList/type.ts
- src/components/organisms/GlobalNavigation/GlobalNavigation.stories.tsx
- src/components/organisms/GlobalNavigation/GlobalNavigation.tsx
- src/components/organisms/GlobalNavigation/type.ts
- src/components/organisms/RichMenu/RIchMenu.tsx
- src/components/organisms/RichMenu/type.ts
GlobalNavigation: GlobalAccount 操作時の処理を追加できるよう修正
https://siva-inc.atlassian.net/browse/TEAMA-235
https://siva-inc.atlassian.net/browse/TEAMA-236
GlobalNavigation: GlobalAccount 操作時の処理を追加できるよう修正
スピード重視で結構無理矢理な実装になっています。。
リストのコンテンツを dashboard 側に寄せるなどリファクタが必要そうな場合は後々対応します
> GlobalNavigation: GlobalAccount 操作時の処理を追加できるよう修正

- package.json
- src/components/atoms/ListItem/const.ts
`ListItem`コンポーネントの`isSelect`時の背景色を`bg-primary-50`から`bg-gray-extraLight`に変更
| 変更前 | 変更後 |
| --- | --- |
| <img width="368" alt="old" src="https://github.com/siva-squad/squad-ui/assets/61968429/91de825a-ca08-48a1-81e6-b9906c3004ab"> | <img width="368" alt="new" src="https://github.com/siva-squad/squad-ui/assets/61968429/acd41f55-d56d-4600-9850-62e76c0c4688"> | 
https://github.com/siva-squad/squadbeyond-frontend/pull/455 <- こちらのタスク内で色変更の要望があったため
選択時は薄い青の方がアクティブ感がわかりやすい気がするんですが、
hover時と同じでグレーにする事になった背景が少し気になります 🧐
> ListItemのisSelect時の色修正

- package.json
- src/components/atoms/ListItem/const.ts
squadbeyond-frontendで使う際に背景色が重なって濃く表示されてしまう(以下の動画参照)ので修正しました
https://github.com/siva-squad/squad-ui/assets/19528768/f86f75b8-aae5-46c4-9399-c43726619c8b
> feat(ListItem):💄ホバー時のスタイルが重なって表示されてしまうため修正

- package.json
- src/components/atoms/ListItem/ListItem.tsx
- src/components/atoms/ListItem/const.ts
- yarn.lock
- タイトル通り
- 経緯
- [呼び出し元](https://github.com/siva-squad/squadbeyond-frontend/blob/89a223b528c0fdfba314203d310e8731382d6016/src/components/layouts/FolderLayout/FolderListSidebar/FolderListSidebar.tsx#L43)側でarbitrary variantsを使用してwidth: 100%を適用しようとする実装をされていたが、実際には子コンポーネントに適用されていなかった
- そもそもui側のclassNameにtruncateが含まれている以上、w-fullは必須
- よってui側で適用するよう修正
- https://siva-inc.atlassian.net/browse/TEAMA-389
> ListItemのラベル部分が親コンポーネントのwidthを引き継いで、truncateが適切に機能するよう修正

- package.json
- src/components/atoms/Input/InputText/type.ts
- Sometimes the attribute `readOnly` is needed when using a text input
- テキスト入力を使用する場合、`readOnly`属性が必要になることがある。
> Add readOnly to type

- package.json
- src/components/molecules/InputElement/InputElement.stories.tsx
- src/components/molecules/InputElement/InputElement.tsx
- src/components/molecules/InputElement/type.ts
現状InputElementのエラー領域はエラー時にのみ出現し、
横並びのアイテム同士が揃わなくなる為表示領域の固定切り替えを追加。
こちらのPRで使用
https://github.com/siva-squad/squadbeyond-frontend/pull/561
> InputElementのエラー表示領域固定切替対応

- package.json
- src/components/atoms/Selector/ForSearch/ForSearch.tsx
- src/components/atoms/Selector/ForSearch/index.ts
- src/components/atoms/Selector/Selector.stories.tsx
- src/components/atoms/Selector/Selector.tsx
- src/components/atoms/Selector/const.ts
- src/components/atoms/Selector/type.ts
Selectorにテキストを直接入力して選択肢の中から検索したい要件があったため対応しました
https://github.com/siva-squad/squad-ui/assets/19528768/343090ea-887f-446e-8721-05edb83a9e52
Selector以下に`ForSearch`コンポーネントを追加しました
`enableSearch`の切り替えで`Selector`, `ForSearch`が切り替わるようになっています
スピード優先でかなり雑な実装になっています
> feat(Selector):✨Selectorでテキストを入力して検索可能にした
