siva-squad/squad-ui

.github/PULL_REQUEST_TEMPLATE.md

プルリクエストのテンプレートを追加した
特になし
- .github/PULL_REQUEST_TEMPLATE.md を追加した
他に必要な項目があればコメントください！

chore: プルリクエストのテンプレートを追加

---

.github/workflows/chromatic_deploy.yml
.github/workflows/publish-package.yml

Chromaticへのデプロイワークフロー内でパス指定を間違えていたため修正しました

chore: Workflow内でのcache-node-modulesのパス指定を修正

---

.github/actions/setup-node/action.yml
.github/workflows/publish-package.yml
package.json

パッケージ配信時のworkflowがエラーで失敗していたため修正した
https://siva-inc.atlassian.net/browse/DSD-28
workflowを以下のように更新
- setup-node
- always-authを有効
- registry-urlを追加
- publish-package
- 使用するsecretsの命名が分かりづらかったため変更

chore: パッケージ配信時のworkflowを修正

---

.storybook/main.ts
package.json
src/components/molecules/LocalMenuItem/LocalMenuItem.stories.tsx
src/components/molecules/LocalMenuItem/LocalMenuItem.tsx
src/components/molecules/LocalMenuItem/const.ts
src/components/molecules/LocalMenuItem/index.ts
src/components/molecules/LocalMenuItem/type.ts
tailwind.config.ts
yarn.lock

LocalMenuItemの実装
https://github.com/siva-squad/squad-ui/assets/61968429/af26d7fc-d103-4fd4-af07-6c066e5f7fcf
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=2404-6042&mode=dev
https://siva-inc.atlassian.net/browse/RPD-14?atlOrigin=eyJpIjoiZGJkNzJlMjE0MTlmNDQ3NDhhOTA0YjAyOTFhNWZiZGYiLCJwIjoiaiJ9
@yoheeeei 
一点preflightについてコメントしてるのでご確認お願いします！

LocalMenuItemの追加

---

src/components/organisms/LocalNavigation/LocalNavigation.stories.tsx
src/components/organisms/LocalNavigation/LocalNavigation.tsx
src/components/organisms/LocalNavigation/index.ts
src/components/organisms/LocalNavigation/type.ts

LocalNavigationコンポーネントをorganismsに追加した
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?node-id=2419%3A7716&mode=dev
https://siva-inc.atlassian.net/browse/RPD-25
- LocalNavigationコンポーネントをorganismsに追加
- storyを追加
---
Added the LocalNavigation component to the organisms.
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?node-id=2419%3A7716&mode=dev
https://siva-inc.atlassian.net/browse/RPD-25
- Added LocalNavigation component to organisms
- Added stories
(No additional notes provided)

feat: LocalNavigationを追加

---

package.json

LocalNavigationコンポーネントをリリースしてしまいたいためパッケージのバージョンを`v0.2.0`に上げました
Raised the package version to `v0.2.0` to release the LocalNavigation component.
現状GitHubでタグをつけたらリリースされる状態になっていますがこの辺りもっと良い感じに運用したいですね...🤔
Currently, the setup is such that a release occurs when a tag is added on GitHub, but I'd like to improve this process...🤔

feat: パッケージバージョンの更新

---

package.json
src/components/atoms/index.ts
src/components/index.ts
src/components/molecules/index.ts
src/components/organisms/index.ts

追加されたコンポーネントがexportされていなかったため追加しました

bug: 各コンポーネントのexportを修正

---

package.json
src/components/molecules/InputElement/InputElement.stories.tsx
src/components/molecules/InputElement/InputElement.tsx
src/components/molecules/InputElement/RequiredBadge/RequiredBadge.stories.tsx
src/components/molecules/InputElement/RequiredBadge/RequiredBadge.tsx
src/components/molecules/InputElement/RequiredBadge/const.ts
src/components/molecules/InputElement/RequiredBadge/index.ts
src/components/molecules/InputElement/RequiredBadge/type.ts
src/components/molecules/InputElement/index.ts
src/components/molecules/InputElement/type.ts
src/hooks/useScreenSize.ts

InputElementの実装
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=1277-1590&mode=design&t=aVdAaKYX6GN7TtDL-4
https://siva-inc.atlassian.net/browse/WE-1
各フィールドの表示切り替えできる仕様でデザイナーさんに確認済みです。

InputElementの実装

---

src/components/atoms/index.ts
src/components/molecules/index.ts
src/components/organisms/GlobalAccount/GlobalAccount.tsx
src/components/organisms/index.ts

- GlobalAccountのbuttonをdiv[role="button"]へ
- ItemElementコンポーネントを始めとする全コンポーネントのexport

コンポーネントのexport追加とhydrationエラー対応処理

---

package.json
src/components/molecules/InputElement/InputElement.stories.tsx
src/components/molecules/InputElement/InputElement.tsx
src/components/molecules/InputElement/type.ts

Added Label to InputElement Component
https://github.com/siva-squad/squadbeyond-frontend/pull/23#discussion_r1395315616

Added Label to InputElement Component

---

src/components/atoms/Button/Button.stories.tsx
src/components/atoms/Button/Button.tsx
src/components/atoms/Button/type.ts
src/components/molecules/InputElement/InputElement.stories.tsx
src/components/molecules/InputElement/InputElement.tsx

#30 
https://siva-inc.atlassian.net/browse/WE-17

ButtonとInputElementの微修正

---

.github/PULL_REQUEST_TEMPLATE.md
package.json

I forgot to increment the version of package.json in the last PR 🙏
Also, I fixed the PR Template to check whether package.json version is updated or not

バージョン上げとPRテンプレートの修正

---

package.json
src/components/atoms/Checkbox/Checkbox.tsx
src/components/atoms/Input/InputNumber/InputNumber.tsx
src/components/atoms/Input/InputText/InputText.tsx
src/components/atoms/Input/Textarea/Textarea.tsx
src/components/atoms/Input/Toggle/Toggle.tsx
src/components/atoms/RadioButton/RadioButton.tsx
src/components/atoms/SearchInput/SearchInput.tsx

Original conversation here 
https://github.com/siva-squad/squadbeyond-frontend/pull/25#discussion_r1400169036

input系要素へのref追加

---

.hygen/new/fc/Component.test.ejs.t

- I added a component test file to be created with hygen when creating a component
- コンポーネント作成時にhygenで作成されるコンポーネント・テスト・ファイルを追加した。
There is no ticket for this, but I thought it might be convenient to have this added. I am not sure which version change to make?
このためのチケットはありませんが、これを追加しておくと便利かもしれないと思いました。どのバージョンを変更すればいいのかわからない。

Add test file to be created with hygen

---

package.json
src/components/atoms/Avatar/Avatar.stories.tsx
src/components/atoms/Avatar/Avatar.tsx
src/components/atoms/Avatar/FullUserCircleIcon/FullUserCircleIcon.tsx
src/components/atoms/Avatar/type.ts
src/components/molecules/Tab/Tab.stories.tsx
src/components/molecules/Tab/Tab.test.tsx
src/components/molecules/Tab/TabArea/TabArea.tsx
src/components/molecules/Tab/TabArea/index.ts
src/components/molecules/Tab/TabArea/type.ts
src/components/molecules/Tab/TabNavigation/TabNavigation.stories.tsx
src/components/molecules/Tab/TabNavigation/TabNavigation.tsx
src/components/molecules/Tab/TabNavigation/const.ts
src/components/molecules/Tab/TabNavigation/index.ts
src/components/molecules/Tab/TabNavigation/type.ts
src/components/molecules/Tab/TabPage/TabPage.tsx
src/components/molecules/Tab/TabPage/index.ts
src/components/molecules/Tab/context.ts
src/components/molecules/Tab/hook.ts
src/components/molecules/Tab/index.ts
src/components/molecules/Tab/type.ts
src/components/molecules/index.ts

ウイイレで使用
\---
Needed for Winning Eleven Project
- Tab Moleculesの作成
\--- Added Tab Molecules
> [!NOTE]
> Tab component could be moved to squadbeyond-frontend perhaps. 
I'm currently checking with the designer to see if we should add the Tab component to DesignSystem.
- Avatarコンポーネントのサイズ調整対応
\--- Added size prop to Avatar component
https://siva-inc.atlassian.net/browse/WE-38

ウイイレ用修正 / Fix for WE Project

---

package.json
src/components/atoms/Badge/Badge.test.tsx

レンダリングのみ（Badgeの機能のみ）のテストを追加
**議論済み**
- Badgeコンポーネントのテストを書いてみましたが、テストを書いていく中で少し迷っています
- ２種類書いてみたんですが、
1. BADGE_CLASS_NAMEを使ったテスト
1. colorとthemeの1つ1つ組み合わせで、意図したclassNameが付いているかのテスト
- みなさんに聞きたいこととしては
- 1はBADGE_CLASS_NAMEがちゃんと動いているかどうかのテストになっている？
- BADGE_CLASS_NAMEの中身を変更して意図しないものになっていたとしてもテストは落ちない
- 2こそテストで確認したいことで、「画面上で意図した色や形になっているか」になっていそうと思うがどうなんだろう？
- 本当に必要なテストが2であった場合、テストが増え過ぎてしまう？
- できれば1くらいのコード量で書きたい 
- 何かいい方法があったりする？
Here's the translation of the provided Japanese text into English:
- I've tried writing tests for the Badge component, but I'm a bit lost in the process of writing them.
- I wrote two types of tests:
1. A test using BADGE_CLASS_NAME
1. Tests for each combination of color and theme to check if the intended className is applied
- What I want to ask everyone is:
- Does test …

add Badge test

---

package.json
src/components/atoms/Selector/type.ts

- idがnumberのみにしていたところ、uidなどのstringもidとして入れられるように修正

fix option id type

---

package.json
src/components/molecules/Dialog/Dialog.stories.tsx
src/components/molecules/Dialog/Dialog.test.tsx
src/components/molecules/Dialog/Dialog.tsx
src/components/molecules/Dialog/type.ts

- squad-ui向上委員会での話の中で、Dialogの中にbuttonがあることによってコントロールしづらく、formの扱いがしづらい
- Mokaさんと話して、デザインシステム上でも問題なく変更いただけたため、squad-uiではDialogのレイアウトと表示のみ変更
- フッター等コンテンツ全てはsquad-uiを使うdashboardで作成する 
- Dialogのstyleがフッターありきのものになっていたため削除し、呼び出し先でstyleをコントロールするように変更
Here's the English translation of the points you've mentioned:
- In the discussion at the Squad-UI Steering Committee, it was noted that having buttons within a Dialog makes control difficult and handling forms challenging.
- After discussing with Moka-san, it was confirmed that there would be no issues with making changes in the design system. Therefore, in Squad-UI, only the layout and display of the Dialog will be modified.
- All content, including the footer, will be created in the dashboard using Squad-UI.
- The style of the Dialog was …

Removed footer from Dialog

---

package.json
src/components/atoms/Anchor/Anchor.stories.tsx
src/components/atoms/Anchor/Anchor.tsx
src/components/atoms/Anchor/const.ts
src/components/atoms/Anchor/type.ts
tailwind.config.ts

- Anchorにテーマ”underline”を追加
- no-backgroundにunderlineをつけたもの
- なし
- なし
- tailwindのconfigにunderlineの色をprimaryに指定するカスタムクラスを追加

Anchorに新たなテーマ "underline"を追加

---

package.json
src/components/atoms/Anchor/Anchor.stories.tsx
src/components/atoms/Anchor/Anchor.tsx
src/components/atoms/Anchor/const.ts
src/components/atoms/Button/Button.stories.tsx
src/components/atoms/Button/Button.tsx
src/components/atoms/Button/const.ts
src/components/atoms/Spinner/const.ts
src/theme/button.ts
src/theme/buttonTheme/compoundVariants.ts
src/theme/buttonTheme/index.ts
src/theme/buttonTheme/type.ts
src/theme/buttonTheme/variants.ts

フッター情報管理ページで使用
Figma: https://www.figma.com/file/8mkhOMue3eAQS6H11k6wQ8/Re-design?type=design&node-id=1994-43748&mode=dev 
JIRA: https://siva-inc.atlassian.net/browse/RDNE-77?atlOrigin=eyJpIjoiZjBlN2QxMTZlMjNlNDc1OTkxZTNhNWI3OTA3ODQyOTEiLCJwIjoiaiJ9
- Button / Anchorに赤枠テーマ追加
- Button / Anchorのスタイルを共通化

Buttonの赤枠テーマ追加

---

package.json
src/components/atoms/Checkbox/Checkbox.tsx
yarn.lock

Checkboxコンポーネントを使用する上で以下のような問題があったため対応を行った
1. チェックボックスアイコンの背景色が設定されておらず、後ろの要素が透けて見えてしまうためデザインの実装の障害になっている
2. childrenを設定していない状態でもchildrenが入る要素が存在してしまうため、デザインの実装の障害になっている
- チェックボックスアイコンの背景が設定されていなかったため`bg-white`を設定
- childrenが存在しない場合はその要素を表示しない

feat: Update Checkbox component styles

---

package.json
src/components/atoms/Input/Toggle/Toggle.stories.tsx
src/components/atoms/Input/Toggle/Toggle.tsx
src/components/atoms/Input/Toggle/const.ts
src/components/atoms/Input/Toggle/type.ts

`Toggle`コンポーネントに対して、コードのフォーマットを行い、小さいサイズのスタイルを追加しました
さらに、各状態に対するStorybookのストーリーを追加しました。
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?node-id=2472%3A5255&mode=dev
- コードフォーマット
- 小さいサイズのオプションを追加
- 各状態に対するStorybookストーリーの追加
---
Formatted the code for the `Toggle` component and added styling for a smaller size. Additionally, stories for each state have been added to Storybook.
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?node-id=2472%3A5255&mode=dev
- Code formatting
- Added option for smaller size
- Added Storybook stories for each state

feat: Add size props to Toggle component

---

package.json
src/components/atoms/SearchInput/const.ts
src/components/molecules/Popover/Popover.stories.tsx
yarn.lock

searchBarのpadding競合修正

---

package.json
src/components/atoms/Selector/Selector.stories.tsx
src/components/atoms/Selector/Selector.tsx
src/components/atoms/Selector/SelectorList/SelectorList.tsx
src/components/atoms/Selector/SelectorList/type.ts
src/components/atoms/Selector/type.ts

全体的に提案ベースのPRです！
マージするかはどちらでも問題ないのですが、一度目を通していただけると幸いです🙇
（+ squad-ui 初PRなので、足らない点あれば教えていただけると嬉しいです🙇）
- Selector: ジェネリクスの適用
- Selector: value の追加
- Selector: OptionType の id の 削除
- Selector: defaultLabel を placeholder に名称変更
以下のように `onSelect`を適用する場合に、`ValueType` が `number or string` だったために型判定をする必要がありそうでした。Selector を直で触る機会は少ないですが、毎度やると面倒かもなので `ValueType` をジェネリクスに変更しています。
```tsx
const handleSelect = (value: string) => {
console.log(value)
}
return (
<Selector
size="small"
options={OPTIONS}
onSelect={(v) => {
/** 
ここで型エラー
以下のように判定すれば出ない
if ( typeof v === 'string' ) handleSelect(v)
*/
handleSelect(v)
}}
defaultLabel={"権限"}
/>
)
```
また Option の型推論もきくようになるイメージです
以下の理由から value を追加しています
- Selector にデフォルト値があった場合に適用できなさそうなため
- 外部の状態を Selector に持ち込めるようにするため
- Selector …

Selector: 型追加とジェネリクスの適用

---

package.json
src/components/atoms/index.ts

タイトル通りです
FavoriteButtonのexportを書き忘れていたため追加しました

feat: Add FavoriteButton export

---

package.json
src/components/molecules/index.ts

- Breadcrumbs: export 追加
- `@siva-development/squad-ui` 経由でインポートできなかったため修正
見当違いだったらすみません！

Breadcrumbs: export 追加

---

package.json
src/components/atoms/SearchInput/const.ts

https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=1202-1672&mode=dev
- SearchInput: 以下のスタイル修正
- border-radius: 8px に修正
- placeholder: テキストカラーを dark-gray に修正

fix: :lipstick: SearchInput: スタイル修正

---

package.json
src/components/atoms/DateRangePicker/DateRangePicker.stories.tsx
src/components/atoms/DateRangePicker/DateRangePicker.test.tsx
src/components/atoms/DateRangePicker/DateRangePicker.tsx
src/components/atoms/DateRangePicker/hooks/index.ts
src/components/atoms/DateRangePicker/hooks/useCalendarCellTheme/index.ts
src/components/atoms/DateRangePicker/hooks/useCalendarCellTheme/useCalendarCellTheme.ts
src/components/atoms/DateRangePicker/hooks/useCalendarSelector/index.ts
src/components/atoms/DateRangePicker/hooks/useCalendarSelector/useCalendarSelector.ts
src/components/atoms/DateRangePicker/hooks/useCalendarSlider/index.ts
src/components/atoms/DateRangePicker/hooks/useCalendarSlider/type.ts
src/components/atoms/DateRangePicker/hooks/useCalendarSlider/useCalendarSlider.stories.tsx
src/components/atoms/DateRangePicker/hooks/useCalendarSlider/useCalendarSlider.tsx
src/components/atoms/DateRangePicker/index.ts
src/components/atoms/DateRangePicker/type.ts
src/components/atoms/DateRangePicker/util.ts
src/components/atoms/DayItem/DayItem.stories.tsx
src/components/atoms/DayItem/DayItem.tsx
src/components/atoms/DayItem/const.ts
src/components/atoms/DayItem/index.ts
src/components/atoms/DayItem/type.ts
src/components/atoms/WeekItem/WeekItem.stories.tsx
src/components/atoms/WeekItem/WeekItem.tsx
src/components/atoms/WeekItem/const.ts
src/components/atoms/WeekItem/index.ts
src/components/atoms/WeekItem/type.ts
src/components/atoms/index.ts
src/index.css
src/utils/date.ts

DateRangePicker: コンポーネント追加
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=1202-1415&mode=dev
RDNE-172
https://siva-inc.atlassian.net/jira/software/projects/RDNE/boards/34?selectedIssue=RDNE-172
DateRangePicker: コンポーネント追加
- 単体選択用の DatePicker については別途実装予定（このPRの実装とフィードバックを参考に）
- 型の影響などで使いづらそうなため
- 統合すると実装が煩雑になりそう？なため
- 少し読みづらいかもです、良さそうな実装方針があれば是非コメントいただきたいです🙇

DateRangePicker: コンポーネント追加

---

.github/workflows/update-release-version.yml
package.json

package.jsonの自動バージョニング対応
続きはもくもく会でやりましょう。
```
act --container-architecture linux/amd64 -P ubuntu-latest=nektos/act-environments-ubuntu:18.04 -j update_version -W .github/workflows/update-release-version.yml
```
- Actionsでのバージョン上げ
- https://zenn.dev/team_zenn/articles/version-up-labeling
- actについて
- https://zenn.dev/yumemi_inc/articles/203779a4eba922
- timezone取得について
- https://qiita.com/itouuuuuuuuu/items/ebf0d4c306b54747374f
- command not foundエラー
- https://www.rasukarusan.com/entry/2021/01/27/224725
- 実行時に`-P ubuntu-latest=nektos/act-environments-ubuntu:18.04` の指定が必要？
- git tagについて
- https://note.com/_umatoma/n/n98657e5c19f4

chore: package.jsonの自動バージョニング対応

---

src/components/molecules/Combobox/Listbox/Listbox.stories.tsx

Remove unused isSelected prop from stories of Listbox.

Remove isSelected from args

---

.github/workflows/update-release-version.yml

自動バージョニングを修正

---

package.json
src/components/molecules/Dialog/Dialog.stories.tsx
src/components/molecules/Dialog/Dialog.tsx
src/components/molecules/Dialog/type.ts

Dialogの可変幅対応
- 通知で使用するダイアログのサイズがコンテンツによって変わるので対応させたい
- 現在の実装だと幅が固定されていて実装できるUIも制限されてしまう
- package.jsonのバージョンはまだ変えてはいけない？
- 以前のボタンprops更新の適応対応が終わっているか

Dialogの可変幅対応

---

package.json
src/components/molecules/NotificationBar/NotificationBar.stories.tsx
src/components/molecules/NotificationBar/NotificationBar.tsx
src/components/molecules/NotificationBar/type.ts

NotificationBar: props の修正
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=2565-6766&mode=design&t=oFMUoz75UxU8ZBFq-4
https://siva-inc.atlassian.net/browse/DSD-74
NotificationBar: props の修正
- isUndoButtonShown を削除
- onClick / onClose / buttonText を optional に変更

NotificationBar: props の修正

---

package.json
src/components/organisms/GlobalNavigation/GlobalNavigation.tsx

GlobalNavigation: deprecated になるようコメントを追記

GlobalNavigaion：deprecated のコメント追加

---

package.json
src/components/atoms/Selector/Selector.tsx
src/components/atoms/Selector/SelectorList/SelectorList.tsx
src/components/atoms/Selector/SelectorList/type.ts
src/components/atoms/Selector/type.ts

既にある情報を編集する際にdefaultValueを使いたかったので追加しました
- propsにdefaultValueを追加
- defaultValueによる値の切り替えを追加

feat(Selector):Add defaultValue props

---

package.json
src/components/atoms/Selector/Selector.tsx
src/components/atoms/Selector/SelectorList/SelectorList.tsx
src/components/atoms/Selector/SelectorList/type.ts
src/components/molecules/MenuList/const.tsx

フロントエンドのテストで関数コンポーネントにref渡すなよと怒られていたので修正しました
- コンポーネントにrefを渡さない形に修正
- パッケージのバージョンを更新

feat(Selector):Change to a form that does not pass ref via props

---

package.json
src/components/molecules/NestContainer/NestContainer.stories.tsx
src/components/molecules/NestContainer/NestContainer.tsx
src/components/molecules/NestContainer/const.ts
src/components/molecules/NestContainer/index.ts
src/components/molecules/NestContainer/type.ts
src/components/molecules/index.ts

NestContainer: コンポーネント追加 / add component
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=5408-15162&mode=dev
https://siva-inc.atlassian.net/browse/DSD-76
NestContainer: コンポーネント追加 / add component

feat: :sparkles: NestContainer: add component

---

package.json
src/components/molecules/Accordion/Accordion.stories.tsx
src/components/molecules/Accordion/Accordion.tsx
src/components/molecules/Accordion/const.ts
src/components/molecules/Accordion/index.ts
src/components/molecules/Accordion/type.ts
src/components/molecules/index.ts

Accordion: コンポーネント追加
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=5408-15163&mode=dev
https://siva-inc.atlassian.net/browse/DSD-75
Accordion: コンポーネント追加 / add component

feat: :sparkles: Accordion: add component
